### ISSUE TITLE
Vince not capable of CPU overclocking

### ISSUE THREAD

**Issue by LuanHalaiko** [Z5X67280/kernel_xiaomi_vince-zucmod#2]
https://github.com/Z5X67280/kernel_xiaomi_vince-zucmod/blob/b261deda6c8b1a842742a8ba11b89512884d75ce/drivers/clk/msm/clock-cpu-8953.c#L134

**Comment by LuanHalaiko** [comment]
Vince is PLL locked to a max 2.2ghz state, the 2.2ghz value is set by qcom as of all qcom processors (ex: snap 435 has a base 1.4big and 1.0little and has a speed bin for 1.5big and 1.2little)

set them all to stock values, and the minimum frequency is 652mhz, it won't go lower since it's locked by PLL

**Comment by Z5X67280** [comment]
OK, I will try it in tomorrow. Thank you. :D

**Comment by Z5X67280** [comment]
We re-edit all freq in v4. Thanks for your tips! :-)
